# Generated by Django 5.0.1 on 2024-11-27 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='weight',
        ),
    ]
